update install notes
the current install instructions fail due to SciPy backward incompatible change:

```
ImportError: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats' (/Users/gregcaporaso/miniconda3/envs/q2-fmt-t1/lib/python3.8/site-packages/scipy/stats/__init__.py)
```